language: python
python:
  - 2.7
install: 
  - pip install .
  - pip install pep8 
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script: 
  - "pep8 --ignore=E501,E225,E128 amazon"
  - "sphinx-build -b html -d _build/doctrees ./docs/ _build/html"
sudo: false 
